// VS Code Feature Registry — full feature spec used by extensions + settings
export const VSCODE_FEATURES = {
  editor: {
    tabCompletion: true,
    intellisense: true,
    codeActions: true,
    formatting: true,
    multicursor: true,
    minimap: true,
    breadcrumbs: true,
    peekDefinition: true,
    renameSymbol: true,
    findReferences: true,
    codeOutline: true,
    foldingRegions: true,
    inlayHints: true,
    parameterHints: true,
    colorDecorators: true,
    linkedEditing: true,
    lensActions: true,
    diffEditor: true,
    splitEditors: true,
    stickyScroll: true,
  },
  terminal: {
    multipleSessions: true,
    shellIntegration: true,
    persistentSessions: true,
    splitTerminals: true,
    terminalProfiles: true,
    linkDetection: true,
    commandHistory: true,
  },
  sidebar: {
    explorer: true,
    search: true,
    sourceControl: true,
    debug: true,
    extensions: true,
    agent: true,
    browser: true,
  },
  statusBar: {
    langMode: true,
    gitBranch: true,
    errorsWarnings: true,
    encoding: true,
    lineColumn: true,
    lspStatus: true,
    indentation: true,
  },
  commandPalette: {
    fuzzySearch: true,
    recentCommands: true,
    keyBindingPreview: true,
  },
  extensions: {
    marketplace: true,
    install: true,
    disable: true,
    recommended: true,
  },
  themes: {
    colorThemes: ["dark-green", "light-coffee"],
    iconThemes: ["vscode-icons"],
  },
} as const;

export const BUILTIN_EXTENSIONS = [
  {
    id: "codeverse.typescript",
    name: "TypeScript & JavaScript",
    description: "Rich editing support, IntelliSense, and snippets for TypeScript and JavaScript",
    category: "Language",
    languages: ["typescript", "javascript", "tsx", "jsx"],
    icon: "⚡",
    version: "1.0.0",
    preinstalled: true,
    enabled: true,
    publisher: "CodeVerse",
  },
  {
    id: "codeverse.react-snippets",
    name: "React & Next.js",
    description: "JSX/TSX snippets, Next.js App Router patterns, and React hooks completions",
    category: "Snippets",
    languages: ["tsx", "jsx", "typescript"],
    icon: "⚛️",
    version: "1.0.0",
    preinstalled: true,
    enabled: true,
    publisher: "CodeVerse",
  },
  {
    id: "codeverse.eslint",
    name: "ESLint",
    description: "Integrates ESLint into CodeVerse with real-time linting",
    category: "Linter",
    languages: ["javascript", "typescript", "jsx", "tsx"],
    icon: "🔍",
    version: "1.0.0",
    preinstalled: true,
    enabled: true,
    publisher: "CodeVerse",
  },
  {
    id: "codeverse.prettier",
    name: "Prettier",
    description: "An opinionated code formatter supporting many languages",
    category: "Formatter",
    languages: ["*"],
    icon: "💅",
    version: "1.0.0",
    preinstalled: true,
    enabled: true,
    publisher: "CodeVerse",
  },
  {
    id: "codeverse.tailwind",
    name: "Tailwind CSS IntelliSense",
    description: "Intelligent Tailwind CSS tooling — autocomplete, syntax highlighting, linting",
    category: "Language",
    languages: ["css", "html", "tsx", "jsx"],
    icon: "🎨",
    version: "1.0.0",
    preinstalled: true,
    enabled: true,
    publisher: "CodeVerse",
  },
  {
    id: "codeverse.gitlens",
    name: "GitLens",
    description: "Supercharge Git inside CodeVerse — blame, history, stash management",
    category: "SCM",
    languages: ["*"],
    icon: "🔗",
    version: "1.0.0",
    preinstalled: true,
    enabled: true,
    publisher: "CodeVerse",
  },
  {
    id: "codeverse.python",
    name: "Python",
    description: "Rich Python support — Pyright LSP, debugging, environments, snippets",
    category: "Language",
    languages: ["python"],
    icon: "🐍",
    version: "1.0.0",
    preinstalled: false,
    enabled: false,
    publisher: "CodeVerse",
  },
  {
    id: "codeverse.rust",
    name: "Rust Analyzer",
    description: "Rust language support with rust-analyzer LSP",
    category: "Language",
    languages: ["rust"],
    icon: "🦀",
    version: "1.0.0",
    preinstalled: false,
    enabled: false,
    publisher: "CodeVerse",
  },
  {
    id: "codeverse.go",
    name: "Go",
    description: "Go language support via gopls language server",
    category: "Language",
    languages: ["go"],
    icon: "🐹",
    version: "1.0.0",
    preinstalled: false,
    enabled: false,
    publisher: "CodeVerse",
  },
  {
    id: "codeverse.docker",
    name: "Docker",
    description: "Dockerfile and docker-compose syntax, snippets, and compose run support",
    category: "Tools",
    languages: ["dockerfile"],
    icon: "🐳",
    version: "1.0.0",
    preinstalled: false,
    enabled: false,
    publisher: "CodeVerse",
  },
] as const;

export const TEMPLATE_REGISTRY = [
  {
    id: "nextjs-app",
    name: "Next.js App",
    description: "Full-stack Next.js 15 with TypeScript, Tailwind CSS, and App Router",
    stack: ["Next.js 15", "TypeScript", "Tailwind CSS"],
    icon: "▲",
    cmd: "npx create-next-app@latest . --typescript --tailwind --app --no-git --yes",
    color: "#000000",
    popular: true,
  },
  {
    id: "react-vite",
    name: "React + Vite",
    description: "Lightning-fast React SPA with Vite, TypeScript, and HMR",
    stack: ["React 19", "Vite 6", "TypeScript"],
    icon: "⚡",
    cmd: "npx create-vite@latest . --template react-ts",
    color: "#646cff",
    popular: true,
  },
  {
    id: "sveltekit",
    name: "SvelteKit",
    description: "Full-stack Svelte app with SvelteKit, TypeScript, and Vite",
    stack: ["SvelteKit", "TypeScript", "Vite"],
    icon: "🧡",
    cmd: "npx sv create . --template minimal --types ts --no-add-ons",
    color: "#ff3e00",
    popular: true,
  },
  {
    id: "astro",
    name: "Astro Site",
    description: "Ultra-fast static site & content platform with Astro and TypeScript",
    stack: ["Astro 4", "TypeScript", "MDX"],
    icon: "🚀",
    cmd: "npx create-astro@latest . --template minimal --typescript strict --no-git --no-install",
    color: "#ff5d01",
    popular: true,
  },
  {
    id: "express-ts",
    name: "Express API",
    description: "Minimal Node.js REST API with Express, TypeScript, and Zod validation",
    stack: ["Node.js", "Express", "TypeScript", "Zod"],
    icon: "🟩",
    cmd: "npx express-generator-typescript .",
    color: "#68a063",
    popular: true,
  },
  {
    id: "turborepo",
    name: "Turborepo Monorepo",
    description: "Full-stack monorepo with Turborepo, shared packages, and multiple apps",
    stack: ["Turborepo", "Next.js", "TypeScript"],
    icon: "🔁",
    cmd: "npx create-turbo@latest . --package-manager npm",
    color: "#ef4444",
    popular: false,
  },
  {
    id: "python-fastapi",
    name: "FastAPI Backend",
    description: "Modern Python API with FastAPI, Pydantic v2, and async support",
    stack: ["Python 3.12", "FastAPI", "Pydantic v2"],
    icon: "🐍",
    cmd: "python3 -m venv venv",
    color: "#009485",
    popular: false,
  },
  {
    id: "django",
    name: "Django App",
    description: "Batteries-included Python web app with Django 5 and REST Framework",
    stack: ["Python 3.12", "Django 5", "DRF"],
    icon: "🌿",
    cmd: "python3 -m venv venv",
    color: "#092e20",
    popular: false,
  },
  {
    id: "go-gin",
    name: "Go API Service",
    description: "High-performance Go REST API with Gin framework and GORM ORM",
    stack: ["Go 1.23", "Gin", "GORM"],
    icon: "🐹",
    cmd: "go mod init myapp && go get github.com/gin-gonic/gin",
    color: "#00add8",
    popular: false,
  },
  {
    id: "rust-axum",
    name: "Rust API",
    description: "Production-ready Rust web API with Axum and Tokio async runtime",
    stack: ["Rust", "Axum", "Tokio"],
    icon: "🦀",
    cmd: "cargo init .",
    color: "#ce422b",
    popular: false,
  },
] as const;
